name: "Upload Dummy SARIF"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to the SARIF file relative to the root of the repository
          sarif_file: dummy-results.sarif
